spring:
   h2:
      console:
         enabled : true
         path : /h2
   datasource:
      url: jdbc:h2:file:~/phonebook
      username: sa
      password: 
      driver-class-name: org.h2.Driver
   jpa:
      show-sql: true
     
      
server:
   servlet:
      context-path: /phonebook/v1